# Generated by Django 5.2.4 on 2025-07-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(max_length=50, verbose_name="Город"),
        ),
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.CharField(max_length=50, verbose_name="Страна"),
        ),
        migrations.AlterField(
            model_name="user",
            name="house_number",
            field=models.CharField(max_length=50, verbose_name="Номер дома"),
        ),
        migrations.AlterField(
            model_name="user",
            name="street",
            field=models.CharField(max_length=50, verbose_name="Улица"),
        ),
    ]
