# Generated by Django 5.2.4 on 2025-07-16 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suppliers",
            name="level",
            field=models.PositiveIntegerField(editable=False, verbose_name="Уровень"),
        ),
    ]
