# Generated by Django 5.2.4 on 2025-07-19 13:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_alter_suppliers_level"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Suppliers",
            new_name="Supplier",
        ),
        migrations.RenameField(
            model_name="supplier",
            old_name="supplier",
            new_name="suppliers",
        ),
    ]
